' if cant not work, use default input method please. (如果无效，运行的时候需要使用系统输入法)
' can use this method to get argument: storePassword = WScript.Arguments(0)
' can use this method to get argument: keyPassword = WScript.Arguments(1)
' WshShell.SendKeys "+" : means press shift key 
' WshShell.SendKeys "{ENTER}" : means press enter key 
'storePassword = "sentryio0328"
'keyPassword = "sentryio0328"

set WshShell = CreateObject("wscript.Shell")
' WshShell.Run "sentryio.keystore_upload_key.bat"
WshShell.Run "java -jar ../../_tools/tools_lib/pepk.jar --keystore=sentryio.keystore --alias=sentryio --output=sentryio.keystore_upload_key.zip --include-cert --encryptionkey=eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a"
WScript.Sleep 1000
WshShell.SendKeys "s"
WshShell.SendKeys "+"
WshShell.SendKeys "e"
WshShell.SendKeys "+"
WshShell.SendKeys "n"
WshShell.SendKeys "+"
WshShell.SendKeys "t"
WshShell.SendKeys "+"
WshShell.SendKeys "r"
WshShell.SendKeys "+"
WshShell.SendKeys "y"
WshShell.SendKeys "+"
WshShell.SendKeys "i"
WshShell.SendKeys "+"
WshShell.SendKeys "o"
WshShell.SendKeys "+"
WshShell.SendKeys "0"
WshShell.SendKeys "+"
WshShell.SendKeys "3"
WshShell.SendKeys "+"
WshShell.SendKeys "2"
WshShell.SendKeys "+"
WshShell.SendKeys "8"
WshShell.SendKeys "+"
WshShell.SendKeys "{ENTER}"
WshShell.SendKeys "s"
WshShell.SendKeys "+"
WshShell.SendKeys "e"
WshShell.SendKeys "+"
WshShell.SendKeys "n"
WshShell.SendKeys "+"
WshShell.SendKeys "t"
WshShell.SendKeys "+"
WshShell.SendKeys "r"
WshShell.SendKeys "+"
WshShell.SendKeys "y"
WshShell.SendKeys "+"
WshShell.SendKeys "i"
WshShell.SendKeys "+"
WshShell.SendKeys "o"
WshShell.SendKeys "+"
WshShell.SendKeys "0"
WshShell.SendKeys "+"
WshShell.SendKeys "3"
WshShell.SendKeys "+"
WshShell.SendKeys "2"
WshShell.SendKeys "+"
WshShell.SendKeys "8"
WshShell.SendKeys "+"
WshShell.SendKeys "{ENTER}"
