name: android_ci_1

on:
  push:
    branches: 
      - main
    # tags:
    #   - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: '选择环境级别的配置变量'
        required: true
        type: environment
        
jobs:
  build:
    name: 编译打包
    runs-on: ubuntu-latest
    # environment: ${{ inputs.environment != '' && inputs.environment || 'dev' }}  # 这种写法不支持
    environment: dev
    steps:
      - name: 打印配置变量
        run: |
          echo -e "\033[36m配置变量:${{ vars.var1 }}\033[0m"
          echo -e "\033[36m配置变量:${{ vars.VAR1 }}\033[0m"

      - name: 拉取代码
        uses: actions/checkout@v4
      
      - name: 其他操作
        run: pwd && ls -t1 app/build/outputs/apk/release
        
      - name: 配置java环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          
      - name: 配置Gradle环境
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      
      - name: gradlew打包
        run: |
          echo -e "gradle版本：$(gradle -v)"
          gradle assembleRelease
          # bash ./gradlew -h
      
      - name: 其他操作
        run: pwd && ls -t1 app/build/outputs/apk/release
