name: test1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: 测试
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    
    - run: |
        echo hello > hello.txt
        echo world > world.txt
    
    - uses: actions/upload-artifact@v3.1.3
      with:
        name: artifact-1
        path: |
          ./hello.txt
          ./world.txt
    
    - uses: actions/upload-artifact@v3.1.3
      with:
        name: artifact-2
        path: |
          ./hello.txt
